const employees = [
    {
       name:'Olajumoke',
       image: 'https://t3.ftcdn.net/jpg/03/28/95/64/360_F_328956433_yDZdQiAVVD7rpYuKaIvhNxK05zI1o.jpg',
       bio: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industryter took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into 0s',
       role: 'CEO',
       empId: '005',
       department: 'Management',
       dateofBirt: '12-Oct-1900',
       dateEnrolled: '22-june-2018',
    },
    {
       name:'Isaiah Bendi',
       image: 'https://t3.ftcdn.net/jpg/03/28/95/64/360_F_328956433_yDZdQiAVVD7rpYuKaIvhNxK05zI1o.jpg',
       bio: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industryter took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into 0s',
       role: 'CEO',
       empId: '005',
       department: 'Management',
       dateofBirt: '12-Oct-1900',
       dateEnrolled: '22-june-2018',
    },
    {
       name:'Mosope Adiamo',
       image: 'https://t3.ftcdn.net/jpg/03/28/95/64/360_F_328956433_yDZdQiAVVD7rpYuKaIvhNxK05zI1o.jpg',
       bio: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industryter took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into 0s',
       role: 'CEO',
       empId: '005',
       department: 'Management',
       dateofBirt: '12-Oct-1900',
       dateEnrolled: '22-june-2018',
    },
    {
       name:'Aisha Suaru',
       image: 'https://t3.ftcdn.net/jpg/03/28/95/64/360_F_328956433_yDZdQiAVVD7rpYuKaIvhNxK05zI1o.jpg',
       bio: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industryter took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into 0s',
       role: 'CEO',
       empId: '005',
       department: 'Management',
       dateofBirt: '12-Oct-1900',
       dateEnrolled: '22-june-2018',
    },
    {
       name:'Jerry Okafor',
       image: 'https://t3.ftcdn.net/jpg/03/28/95/64/360_F_328956433_yDZdQiAVVD7rpYuKaIvhNxK05zI1o.jpg',
       bio: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industryter took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into 0s',
       role: 'CEO',
       empId: '005',
       department: 'Management',
       dateofBirt: '12-Oct-1900',
       dateEnrolled: '22-june-2018',
    },
    {
       name:'Olajumoke',
       image: 'https://t3.ftcdn.net/jpg/03/28/95/64/360_F_328956433_yDZdQiAVVD7rpYuKaIvhNxK05zI1o.jpg',
       bio: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industryter took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into 0s',
       role: 'CEO',
       empId: '005',
       department: 'Management',
       dateofBirt: '12-Oct-1900',
       dateEnrolled: '22-june-2018',
    },
   ]

   export default employees